---
jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - template: .ci/steps/ubuntu/install-prereqs.yml
    - template: .ci/steps/ubuntu/build.yml
    - template: .ci/steps/ubuntu/test.yml
  - job: OSX
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - template: .ci/steps/mac/install-prereqs.yml
    - template: .ci/steps/mac/build.yml
    - template: .ci/steps/mac/test.yml